import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

test("composite GitHub Action exposes CI outputs", () => {
  const action = fs.readFileSync("action.yml", "utf8");

  assert.match(action, /outputs:/);
  assert.match(action, /status:/);
  assert.match(action, /total:/);
  assert.match(action, /passed:/);
  assert.match(action, /failed:/);
  assert.match(action, /summary:/);
  assert.match(action, /pr-comment:/);
  assert.match(action, /bundle:/);
  assert.match(action, /bundle-sections:/);
  assert.match(action, /review-baseline:/);
  assert.match(action, /review-candidate:/);
  assert.match(action, /review:/);
  assert.match(action, /review-sections:/);
  assert.match(action, /default: summary,scan,tool-calls,workflow,filters,timeline/);
  assert.match(action, /review-fail-on-failure:/);
  assert.match(action, /scan:/);
  assert.match(action, /scan-fail-on:/);
  assert.match(action, /sarif:/);
  assert.match(action, /bundle-manifest:/);
  assert.match(action, /--scan/);
  assert.match(action, /--scan-fail-on/);
  assert.match(action, /--sarif/);
  assert.match(action, /--pr-comment-md/);
  assert.match(action, /bundle_args=\(bundle/);
  assert.match(action, /review_args=\(review/);
  assert.match(action, /review-pr-comment/);
  assert.match(action, /review-bundle-manifest/);
  assert.match(action, /--sections/);
  assert.match(action, /--json/);
  assert.match(action, /GITHUB_OUTPUT/);
  assert.match(action, /actions\/setup-node@v6/);
  assert.doesNotMatch(action, /actions\/setup-node@v4/);
  assert.doesNotMatch(action, /your-org\/agentlens@v0/);
});

test("repository workflow verifies GitHub Action outputs", () => {
  const workflow = fs.readFileSync(".github/workflows/ci.yml", "utf8");

  assert.match(workflow, /id: agentlens-action/);
  assert.match(workflow, /steps\.agentlens-action\.outputs\.status/);
  assert.match(workflow, /steps\.agentlens-action\.outputs\.failed/);
  assert.match(workflow, /steps\.agentlens-action\.outputs\.total/);
  assert.match(workflow, /steps\.agentlens-action\.outputs\.bundle/);
  assert.match(workflow, /steps\.agentlens-action\.outputs\.bundle-manifest/);
  assert.match(workflow, /steps\.agentlens-action\.outputs\.review/);
  assert.match(workflow, /steps\.agentlens-action\.outputs\.review-pr-comment/);
  assert.match(workflow, /steps\.agentlens-action\.outputs\.review-bundle/);
  assert.match(workflow, /steps\.agentlens-action\.outputs\.review-bundle-manifest/);
  assert.match(workflow, /pr-comment\.md/);
  assert.match(workflow, /agentlens-ci-comment/);
  assert.match(workflow, /action-bundle/);
  assert.match(workflow, /action-review/);
  assert.match(workflow, /manifest\.json/);
  assert.match(workflow, /actions\/checkout@v7/);
  assert.match(workflow, /actions\/setup-node@v6/);
  assert.match(workflow, /demo:autogen/);
  assert.match(workflow, /demo:crewai/);
  assert.match(workflow, /demo:regression-pr/);
  assert.match(workflow, /review-baseline:/);
  assert.match(workflow, /review-candidate:/);
  assert.match(workflow, /bundle-sections: summary,scan,tool-calls,workflow,timeline/);
  assert.match(workflow, /review-sections: summary,scan,tool-calls,workflow,timeline/);
  assert.match(workflow, /multi-agent-basic\.json/);
  assert.doesNotMatch(workflow, /actions\/checkout@v4/);
  assert.doesNotMatch(workflow, /actions\/setup-node@v4/);
});
